<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>AgentLink.Setup</AssemblyName>
    <RootNamespace>RayLink.Setup</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeAllContentForSelfExtract>false</IncludeAllContentForSelfExtract>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <Version>0.3.6</Version>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\artifacts\win-x64-single\AgentLink.exe" LogicalName="payload\AgentLink.exe" />
    <EmbeddedResource Include="..\..\native\iroh-transport\target\x86_64-pc-windows-msvc\release\raylink-iroh-transport.exe" LogicalName="payload\AgentLink.Transport.exe" />
  </ItemGroup>
</Project>
